import { useState } from 'react';
import { Activity, ArrowRight, Brain, Check, FileText, HeartPulse, Menu, Moon, Sun, Upload, X } from 'lucide-react';

const pages = ['Home', 'Analysis', 'About', 'More Info', 'Login', 'Register'] as const;
type Page = typeof pages[number];

function Header({ page, setPage }: { page: Page; setPage: (page: Page) => void }) {
  const [dark, setDark] = useState(false); const [menu, setMenu] = useState(false);
  return <header className="site-header"><a className="brand" href="#home" onClick={() => setPage('Home')}><span className="brand-mark"><Activity size={22}/></span><span>LungVision <b>AI</b></span></a><button className="menu-toggle" aria-label="Toggle menu" onClick={() => setMenu(!menu)}>{menu ? <X/> : <Menu/>}</button><nav className={menu ? 'site-nav open' : 'site-nav'}>{pages.map(item => <button key={item} className={page === item ? 'nav-link active' : 'nav-link'} onClick={() => {setPage(item); setMenu(false)}}>{item === 'More Info' ? item : item}</button>)}<a className="nav-link" href="/documentation">Documentation</a></nav><button className="theme-button" aria-label="Toggle color mode" onClick={() => {setDark(!dark); document.body.classList.toggle('dark-mode')}}>{dark ? <Sun size={18}/> : <Moon size={18}/>}</button></header>
}

function Home({ setPage }: { setPage: (page: Page) => void }) {
 return <><section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="pulse-dot"/> MULTIMODAL LUNG CANCER DETECTION</div><h1>Earlier insight.<br/><em>Clearer direction.</em></h1><p>AI-assisted analysis of CT scans, chest X-rays, and clinical data to support research and informed conversations with healthcare professionals.</p><button className="primary-action" onClick={() => setPage('Analysis')}>Start Diagnosis <ArrowRight size={18}/></button><div className="hero-note"><HeartPulse size={17}/> Research and educational use</div></div><div className="hero-visual"><div className="scan-frame"><div className="scan-grid"/><img src="/images/xray-lung.jpeg" alt="Chest X-ray example"/><div className="scan-label"><span/> IMAGING ANALYSIS</div><div className="scan-corner top-left"/><div className="scan-corner bottom-right"/></div><div className="floating-tag"><Brain size={18}/><span><b>Multimodal</b><small>AI analysis</small></span></div></div></section><section className="content-section" id="about-project"><div className="section-heading"><span className="eyebrow">ABOUT THE PROJECT</span><h2>One platform. Multiple perspectives.</h2><p>LungVision combines image and clinical data workflows to explore lung cancer detection with machine learning.</p></div><div className="feature-grid"><article className="feature-card"><div className="feature-icon"><Upload/></div><h3>Upload Data</h3><p>Submit CT scans, chest X-rays, or clinical information through the diagnosis workflow.</p></article><article className="feature-card"><div className="feature-icon"><Brain/></div><h3>AI Analysis</h3><p>Trained image models and a clinical data model perform the analysis on the backend.</p></article><article className="feature-card"><div className="feature-icon"><FileText/></div><h3>Review Results</h3><p>Explore model outputs, consensus findings, explainability maps, and downloadable reports.</p></article></div></section><section className="start-band"><div><span className="eyebrow">LUNGVISION AI</span><h2>Explore the analysis workflow</h2><p>Sign in to submit an analysis using the available trained models.</p></div><button className="primary-action" onClick={() => setPage('Analysis')}>Go to Analysis <ArrowRight size={18}/></button></section><footer className="site-footer"><span>© LungVision AI</span><span>Research and educational use only</span><a href="/documentation">Documentation</a></footer></>
}

const clinicalFields = ['GENDER','AGE','SMOKING','YELLOW_FINGERS','ANXIETY','PEER_PRESSURE','CHRONIC DISEASE','FATIGUE','ALLERGY','WHEEZING','ALCOHOL CONSUMING','COUGHING','SHORTNESS OF BREATH','SWALLOWING DIFFICULTY','CHEST PAIN'];
function Analysis() {
 const [scanType, setScanType] = useState('ct'); const [file, setFile] = useState<File | null>(null); const [preview, setPreview] = useState(''); const [drag, setDrag] = useState(false);
 const choose = (f?: File) => { if (!f) return; setFile(f); setPreview(URL.createObjectURL(f)); };
 return <main className="analysis-page"><div className="analysis-heading"><span className="eyebrow">MULTIMODAL ANALYSIS</span><h1>Diagnosis</h1><p>Submit imaging or clinical information for analysis by the available trained models.</p></div><div className="analysis-shell"><div className="analysis-top"><div><h2>Choose analysis type</h2><p>Select the data type you want to analyze.</p></div><select value={scanType} onChange={e => setScanType(e.target.value)}><option value="ct">CT Scan</option><option value="xray">Chest X-ray</option><option value="metadata">Clinical Data</option></select></div><form action={scanType === 'metadata' ? '/predict_metadata_form' : '/diagnosis'} method="post" encType="multipart/form-data" className="analysis-form"><input type="hidden" name="scan_type" value={scanType}/>{scanType !== 'metadata' ? <><div className="upload-area" onDragOver={e => {e.preventDefault();setDrag(true)}} onDragLeave={() => setDrag(false)} onDrop={e => {e.preventDefault();setDrag(false);choose(e.dataTransfer.files[0])}} onClick={() => document.getElementById('scan-file')?.click()} style={{borderColor: drag ? '#007bff' : undefined}}>{preview ? <img className="upload-preview" src={preview} alt="Selected scan preview"/> : <><span className="upload-icon"><Upload/></span><h3>Drop your scan here</h3><p>or browse your files</p><small>Image file · maximum 16 MB</small></>}<input id="scan-file" name="image" type="file" accept="image/*" hidden required onChange={e => choose(e.target.files?.[0])}/></div>{file && <div className="selected-file">{file.name}<button type="button" onClick={() => {setFile(null);setPreview('')}}>Remove</button></div>}<button className="primary-action submit-action" type="submit" disabled={!file}>Analyze scan <ArrowRight size={18}/></button><p className="form-note">You need to be signed in. The existing Flask service runs inference and renders its results page.</p></> : <><p className="form-note">Enter the same clinical factors used by the existing clinical model.</p><div className="clinical-grid">{clinicalFields.map(field=><label key={field}>{field}<select name={field} defaultValue={field==='AGE' ? '50' : field==='GENDER' ? 'M' : 'No'} required>{field==='AGE' ? Array.from({length:108},(_,i)=><option key={i} value={i+13}>{i+13}</option>) : field==='GENDER' ? <><option value="M">Male</option><option value="F">Female</option></> : <><option value="No">No</option><option value="Yes">Yes</option></>}</select></label>)}</div><button className="primary-action submit-action" type="submit">Analyze clinical data <ArrowRight size={18}/></button><p className="form-note">The Flask route returns a rendered HTML result. This React client does not invent result values.</p></>}</form></div></main>
}

function About({ more = false }: {more?: boolean}) { return <main className="simple-page"><span className="eyebrow">LUNGVISION AI</span><h1>{more ? 'More About Lung Cancer' : 'About LungVision'}</h1><div className="analysis-shell"><p>{more ? 'Lung cancer is a disease in which abnormal cells grow in the lungs. Learn more from the World Health Organization.' : 'A multimodal research application for exploring lung cancer detection from chest imaging and clinical data.'}</p><p>Image and clinical models run in the existing Python backend. Explainability features include Grad-CAM and LIME when available.</p><p className="form-note">This system is for research and educational use. It does not replace professional medical advice.</p><a className="text-link" href={more ? 'https://www.who.int/news-room/fact-sheets/detail/lung-cancer' : '/documentation'}>{more ? 'World Health Organization' : 'View project documentation'} <ArrowRight size={16}/></a></div></main> }

function Auth({ register, done }: {register:boolean; done:()=>void}) { const [error,setError]=useState(''); const [busy,setBusy]=useState(false); return <main className="simple-page"><span className="eyebrow">LUNGVISION AI ACCOUNT</span><h1>{register?'Create your account':'Welcome back'}</h1><form className="analysis-shell auth-form" onSubmit={async e=>{e.preventDefault();setError('');setBusy(true);const form=new FormData(e.currentTarget);const body=register?{fullName:String(form.get('fullName')),email:String(form.get('email')),password:String(form.get('password')),role:String(form.get('role'))}:{email:String(form.get('email')),password:String(form.get('password'))};try{const response=await fetch(register?'/register':'/login',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify(body)});const data=await response.json();if(!response.ok||!data.success)throw new Error(data.error||'Unable to complete request');done()}catch(err){setError(err instanceof Error?err.message:'Request failed')}finally{setBusy(false)}}}>{register&&<label>Full name<input className="auth-input" name="fullName" autoComplete="name" required maxLength={60}/></label>}<label>Email<input className="auth-input" name="email" type="email" autoComplete="email" required/></label><label>Password<input className="auth-input" name="password" type="password" autoComplete={register?'new-password':'current-password'} minLength={register?8:1} required/></label>{register&&<label>Role<select className="auth-input" name="role" required><option value="Patient">Patient</option><option value="Clinician">Clinician</option><option value="Researcher">Researcher</option></select></label>}{error&&<p className="error">{error}</p>}<button className="primary-action submit-action" disabled={busy}>{busy?'Please wait…':register?'Create account':'Sign in'} <ArrowRight size={18}/></button><p className="form-note">{register?'Password needs 8 characters, an uppercase letter, a number, and a special character.':'Sign in uses the existing Flask session.'}</p></form></main> }

export default function App() { const [page, setPage] = useState<Page>('Home'); return <div className="app"><Header page={page} setPage={setPage}/>{page==='Home'?<Home setPage={setPage}/>:page==='Analysis'?<Analysis/>:page==='About'?<About/>:page==='More Info'?<About more/>:<Auth register={page==='Register'} done={()=>setPage('Analysis')}/>}</div> }


